language: cpp

compiler:
  - gcc
  - clang

env:
  - VARIANT=debug
  - VARIANT=release

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - echo -e 'import boost ;\nboost.use-project ;\n using gcc ;\n using clang ;\n using python ;' > ~/user-config.jam
  - cat ~/user-config.jam
  - wget https://github.com/boostorg/build/raw/develop/src/contrib/boost.jam -O ~/boost.jam

install:
  # Use GCC 4.8.
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - sudo apt-get install -qq libboost1.48-all-dev python-dev
  - if [ "$CXX" = "g++" ]; then
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90;
    fi
  - sudo apt-get install -qq libboost-all-dev

# It just so happens that ${CC} corresponds to the Boost.Build toolset name.
script: bjam test toolset=${CC} variant=${VARIANT}
